apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-anyuid-scc-datapower
  namespace: datapower
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-anyuid-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-anyuid-scc-datapower
  namespace: datapower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-anyuid-scc-datapower
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:datapower
- kind: ServiceAccount
  name: default
  namespace: datapower
