apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-restricted-scc-eventstreams
  namespace: eventstreams
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-restricted-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-restricted-scc-eventstreams
  namespace: eventstreams
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-restricted-scc-eventstreams
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:eventstreams
- kind: ServiceAccount
  name: default
  namespace: eventstreams
