# Whether the application is running production workloads
productionDeployment: PRODUCTION_DEPLOY

image:
  repository: "IMAGE_REGISTRY"
  pullSecret: "PULL_SECRET"

rbac:
  serviceAccountName: ibm-aspera-hsts-icp4i

arch:
  amd64: "3 - Most preferred"

deployRedis: true
# If not deploying redis, specify the host and port of an existing redis host
redisHost: ""
redisPort: 6379

# Values for redis subchart.
# Used when deployRedis is true
redis:
  serviceAccount:
    create: false
    name: ibm-aspera-hsts-icp4i
  persistence:
    enabled: false
    useDynamicProvisioning: USE_DYNAMIC_PROVISIONING
    existingClaimName: ""
    accessMode: ReadWriteMany
    storageClassName: "FILE_STORAGE"
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-redis
    tag: 4.0.12-rhel-amd64
    pullPolicy: IfNotPresent
    pullSecret: "PULL_SECRET"
  rbac:
    create: false
  serviceAccount:
    create: false
    name: ibm-aspera-hsts-icp4i
  resources:
    server:
      requests:
        memory: 100Mi
        cpu: ".01"
      limits:
        memory: 5Gi
        cpu: ".2"
    sentinel:
      requests:
        memory: 5Mi
        cpu: ".005"
      limits:
        memory: 100Mi
        cpu: '.02'

tls:
  issuer: ""

ingress:
  hostname: INGRESS_HOSTNAME
  tlsSecret: ""

# asconfigurator commands to be run on each aspera.conf
asperaconfig: []

# Optional secret containing server sshd public/private keys
# Secret keys used:
# - ssh_host_rsa_key
# - ssh_host_rsa_key.pub
sshdKeysSecret: ""

# If desired, set different storage configuration for Aspera transfer storage
# Otherwise, will default to values under global.persistence
persistence:
  useDynamicProvisioning: USE_DYNAMIC_PROVISIONING
  storageClassName: FILE_STORAGE
  size: 10Gi
  existingClaimName: ''
  mountPath: /asperanode
  fsGroup: 1001

asperanode:
  clusterId: ""
  httpsPort: 9092
  nodeCount: REPLICAS
  serverSecret: SERVER_SECRET
  nodeAdminSecret: NODE_ADMIN_SECRET 
  accessKeySecret: ACCESSKEY_SECRET

  # See: http://download.asperasoft.com/download/docs/entsrv/3.9.1/es_admin_linux/webhelp/index.html#dita/access_key_auth.html
  # This corresponds to the "configuration" section of the access key json
  # By default only target_rate_kbps is set
  accessKeyConfig: {}

  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-asperanode
    tag: 3.9.1-rhel-amd64
    pullPolicy: IfNotPresent

  autoscale:
    api:
      enabled: false
      minReplicas: REPLICAS
      maxReplicas: REPLICAS
      cpuAverageUtilization: 50
  resources:
    requests:
      memory: 100Mi
      cpu: '.02'
    limits:
      memory: 700Mi
      cpu: '0.6'

dashboard:
  enabled: true

aej:
  kafkaHost: "PROXY_ENDPOINT"
  kafkaPort: KAFKAPORT
  kafkaProtocol: PLAINTEXT
  kafkaSaslMechanism: PLAIN
  kafkaAuthSecret: ""
  kafkaCertSecret: ""
  replicas: REPLICAS 
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-aej
    tag: 3.9.1-rhel-amd64
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP

prometheusEndpoint:
  replicas: REPLICAS
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-prometheus-endpoint
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

  service:
    api:
      type: ClusterIP
      port: 2112
  config:
    listenAddr: ":2112"

stats:
  replicas: REPLICAS
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-stats
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

  service:
    api:
      type: ClusterIP
      port: 80

ascpLoadbalancer:
  replicas: REPLICAS
  strategy: MIN_SESSIONS
  service:
    type: ClusterIP
    port: 80

utils:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-utils
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent


ascpSwarm:
  replicas: REPLICAS
  service:
    type: ClusterIP
    port: 80
  config:
    hostPortMin: 34001
    hostPortMax: 34101
    minAvailable: 1
    maxRunning: REPLICAS
    member:
      name:
        prefix: ""
    nodeLabels: {-node-role.kubernetes.io/ASCP_NODE_LABEL: "true"}

loadbalancer:
  image:
      repository: "IMAGE_REGISTRY"
      name: aspera-hsts-loadbalancer
      tag: 1.2.2-rhel-amd64
      pullPolicy: IfNotPresent


nodedLoadbalancer:
  replicas: REPLICAS
  strategy: MIN_SESSIONS
  service:
    type: ClusterIP
    port: 80

swarm:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-swarm
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent


nodedSwarm:
  replicas: REPLICAS
  service:
    type: ClusterIP
    port: 80
  config:
    minAvailable: 1
    maxRunning: REPLICAS
    member:
      name:
        prefix: ""
    nodeLabels: {-node-role.kubernetes.io/NODED_NODE_LABEL: "true"}

firstboot:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-firstboot
    tag: 3.9.1-rhel-amd64
    pullPolicy: IfNotPresent

nodedSwarmMember:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-noded-swarm-member
    tag: 3.9.1-rhel-amd64
    pullPolicy: IfNotPresent

receiver:
  authorizedKeys: []
  vlinks: []
  swarm:
    image:
      repository: "IMAGE_REGISTRY"
      name: aspera-hsts-receiver-swarm-member
      tag: 3.9.1-rhel-amd64
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 50Mi
        cpu: '.01'
      limits:
        memory: 700Mi
        cpu: '0.5'

httpProxy:
  replicas: REPLICAS
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-http-proxy
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

  listenAddr: ":8000"
  service:
    api:
      type: ClusterIP
      port: 9092

tcpProxy:
  replicas: REPLICAS
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-tcp-proxy
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

  listenAddr: ":8022"
  service:
    type: LoadBalancer
    port: 33001

probe:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-probe
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

election:
  image:
    repository: "IMAGE_REGISTRY"
    name: aspera-hsts-election
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent

rproxy:
  address: "RPROXY_ADDRESS"

# Not intended to be changed
# Ensures that ibm-sch secret generation works when using an appName override
nameOverride: aspera-hsts

sch:
  rbac:
    serviceAccountName: ibm-sch-secret-gen
  global:
    image:
      repository: "IMAGE_REGISTRY"
  image:
    name: aspera-hsts-utils
    tag: 1.2.2-rhel-amd64
    pullPolicy: IfNotPresent
    pullSecret: "PULL_SECRET"
