apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-anyuid-hostpath-scc-apic
  namespace: apic
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-anyuid-hostpath-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-anyuid-hostpath-scc-apic
  namespace: apic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-anyuid-hostpath-scc-apic
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:apic
- kind: ServiceAccount
  name: default
  namespace: apic
