apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anyuid-tracing
  namespace: tracing
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anyuid-tracing
  namespace: tracing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anyuid-tracing
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:tracing
- kind: ServiceAccount
  name: default
  namespace: tracing
