###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "ibm-wcd-redis.sch.chart.config.values") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sch.names.fullCompName" (list . .sch.chart.components.sentinel) | quote }}
  labels:
{{  include "sch.metadata.labels.standard" (list . .sch.chart.components.sentinel) | indent 4 }}
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    service: {{ include "sch.names.fullCompName" (list . .sch.chart.components.sentinel) }}
