###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{- include "sch.config.init" (list . "ibm-wcd-redis.sch.chart.config.values") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sch.names.statefulSetName" (list . .sch.chart.components.sentinel) | quote }}
  labels:
{{  include "sch.metadata.labels.standard" (list . .sch.chart.components.sentinel) | indent 4 }}
spec:
  replicas: {{ .Values.replicas.sentinels }}
  selector:
    matchLabels:
{{  include "sch.metadata.labels.standard" (list . .sch.chart.components.sentinel) | indent 6 }}
  serviceName: "{{ template "redis.fullname" . }}-sentinel-svc"
  template:
    metadata:
      annotations:
        productID: RedisHA_406r0_free_00000
        productName: Redis HA
        productVersion: 3.2.12-r0
      labels:
        service: {{ include "sch.names.fullCompName" (list . .sch.chart.components.sentinel) }}
{{ include "sch.metadata.labels.standard" (list . .sch.chart.components.sentinel) | indent 8 }}
    spec:
      affinity:
{{- include "redis.nodeaffinity" . | indent 8 }}
      serviceAccountName: {{ template "redis-ha.serviceAccountName" . }}
{{- if include "redis.pullSecret" . }}
      imagePullSecrets:
      - name: {{ include "redis.pullSecret" . | quote }}
{{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 8000
      containers:
      - name: sentinel
        image: {{ include "redis.image.server" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 8000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          initialDelaySeconds: {{ .Values.sentinel.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.sentinel.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.sentinel.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.sentinel.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.sentinel.livenessProbe.failureThreshold }}
          exec:
            command:
            - redis-cli
            - "-p"
            - "26379"
            - SENTINEL
            - masters
        readinessProbe:
          initialDelaySeconds: {{ .Values.sentinel.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.sentinel.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.sentinel.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.sentinel.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.sentinel.readinessProbe.failureThreshold }}
          exec:
            command:
            - redis-cli
            - "-p"
            - "26379"
            - SENTINEL
            - masters
        resources:
{{ toYaml .Values.resources.sentinel | indent 10 }}
        env:
          - name: SENTINEL
            value: "true"
          - name: REDIS_PASSWORD
            value: {{ include "redis.password" . | quote }}
          - name: CHART_NAME
            value: {{ .sch.chart.appName }}
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HELM_RELEASE
            value: {{ .Release.Name }}
          - name: REDIS_MASTER_SERVICE
            value: {{ include "sch.names.fullCompName" (list . .sch.chart.components.master) | quote }}
          - name: REDIS_MASTER_SERVICE_PORT
            value: "6379"
        ports:
          - containerPort: 26379
