{{/*
###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
*/}}
{{- if .Values.serviceAccount.create -}}
{{- include "sch.config.init" (list . "ibm-wcd-redis.sch.chart.config.values") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis-ha.serviceAccountName" . }}
  labels:
{{ include "redis.labels.standard" . | indent 4 }}
{{- end -}}
