# © Copyright IBM Corporation 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

license: "accepted"

global:
  designerFlowsOperationMode: 'local'
  replicaCount: REPLICA_COUNT
  appConnectURL:
  appConnectInstanceID:
  appConnectSecret:

icp4iNamespace: integration

featureTogglesOverride:

###########################################################
# Ingress settings
###########################################################

image:
  # name of the dashboard image
  fireflyFlowdocAuthoring: IMAGE_REGISTRY/ibm-app-connect-flowdoc-authoring-prod:11.0.0.8-r1
  # name of the flow test manager image
  fireflyFlowTestManager: IMAGE_REGISTRY/ibm-app-connect-flow-test-manager-prod:11.0.0.8-r1
  # name of the runtime image
  fireflyRuntime: IMAGE_REGISTRY/ibm-app-connect-runtime-prod:11.0.0.8-r1
  # name of the ui image
  fireflyUi: IMAGE_REGISTRY/ibm-app-connect-ui-prod:11.0.0.8-r1
  # name of the connector auth service image
  connectorAuthService: IMAGE_REGISTRY/ibm-app-connect-connector-auth-service-prod:11.0.0.8-r1
  # proxy image to provide SSL
  proxy: IMAGE_REGISTRY/ibm-app-connect-proxy-prod:11.0.0.8-r1
  # name of the image that runs as a job to configure ICP
  configurator: IMAGE_REGISTRY/ibm-acecc-configurator-prod:11.0.0.8-r1
  # pullPolicy of IfNotPresent causes image pulling to be skipped if it already exists. Change to Always to force a pull.
  pullPolicy: IfNotPresent
  # pullSecret is the secret to use when pulling the image from a private registry
  pullSecret: PULL_SECRET

###########################################################
# ibm-ace-server specific values.
###########################################################
ibm-ace-server-dev:
  license: "accept"
  customContentServer: true
  adminServerSecure: true # The admin server runs securely and we need to connect to it using SSL to gather statistics
  aceonly:
    replicaCount: 1
  designerFlowsOperationMode: 'all'
  log:
    format: basic
  dashboardEnabled: true # Don't import the MQ dashboards
  integrationServer:
    keystoreKeyNames: iskey
  image:
    aceonly: IMAGE_REGISTRY/ibm-ace-server-dev:11.0.0.8-r1
    configurator: IMAGE_REGISTRY/ibm-acecc-configurator-dev:11.0.0.8-r1
    designerflows: IMAGE_REGISTRY/ibm-ace-designer-flows-dev:11.0.0.8-r1
    proxy: IMAGE_REGISTRY/ibm-app-connect-proxy-dev:11.0.0.8-r1
    connectors: IMAGE_REGISTRY/ibm-ace-lcp-dev:11.0.0.8-r1
    pullPolicy: IfNotPresent
    pullSecret: PULL_SECRET
  service:
    type: ClusterIP

###########################################################
# CouchDB specific values.
###########################################################
couchdb:
  initImage:
    repository: busybox
    tag: 1
  # Enabling this blocks the UI
  couchdbConfig:
    ssl:
      port: 6984
      enable: true
      key_file: /ssl/certs/server.key
      cert_file: /ssl/certs/server.crt
      cacert_file:  /ssl/certs/cacert.crt
    chttpd:
      require_valid_user: true
  image:
    repository: IMAGE_REGISTRY/ibm-couchdb2
    tag: 2.3.1
    pullPolicy: IfNotPresent
    pullSecret: PULL_SECRET
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: BLOCK_STORAGE

###########################################################
# flow doc authoring specific settings
###########################################################
fireflyFlowdocAuthoring:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

###########################################################
# flow test manager specific settings
###########################################################
fireflyFlowTestManager:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

###########################################################
# runtime specific settings
###########################################################
fireflyRuntime:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

###########################################################
# ui specific settings
###########################################################
fireflyUi:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

###########################################################
# connectorAuthService specific settings
###########################################################
connectorAuthService:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

###########################################################
# Stunnel proxy specific settings
###########################################################
proxy:
  # resource limits to apply to the control ui containers
  # ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1024Mi

arch: amd64
ssoEnabled: true
dashboardEnabled: true
