appVersion: 2020.1.1
description: A Helm chart for the IBM Cloud Pak for Integration Navigator
icon: https://github.com/IBM/charts/raw/master/entitled/ibm-icp4i-prod/ibm_cloud_pak/logo/app-icon-light-theme.png
keywords:
- ACE
- API
- API Connect
- App Connect
- Application
- Aspera
- ICP4I
- Cloud Pak for Integration
- Commercial
- Connect
- Data
- DataPower
- Event Streams
- Events
- ICPRHOCP
- ICPROKS
- Insight
- Integration
- MQ
- Messaging
- Navigator
- Platform
- Transfer
- amd64
kubeVersion: '>=1.14'
name: ibm-icp4i-prod
tillerVersion: '>=2.9.1'
version: 3.1.0
